[package]
name = "rust-ostree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffi = "0.1.1"
fuser = "0.14.0"
gio = "0.18.4"
libc = "0.2.151"
ostree = "0.19.1"
time = "0.1"
